"""Initial migration with Film, Benutzer, and LendingRequest models

Revision ID: 15f22502412d
Revises: 
Create Date: 2025-10-29 14:47:47.916022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f22502412d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('tmdb_id', sa.String(length=20), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('besitzer', sa.String(length=100), nullable=True),
    sa.Column('verliehen_an', sa.String(length=100), nullable=True),
    sa.Column('verliehen_seit', sa.DateTime(), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.Column('wunschliste', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lending_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lending_request')
    op.drop_table('film')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
